version: "3"
services:
  db:
    container_name: "chama-na-playlist-backend"
    image: "postgres:11.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_MULTIPLE_DATABASES=production,test
